name: ml-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip=25.0
  - pip:
      - cloudpickle==3.1.1
      - joblib==1.4.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - numpy==2.2.2
      - pandas==2.2.3
      - mlflow==2.20.1
      - pre-commit==4.1.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - pydantic==2.10.6
      - azureml-core==1.59.0
      - virtualenv==20.29.1
      - setuptools==75.8.0
      - azureml-inference-server-http==1.4.0
