name: Deploy ML Model to Azure ML Studio

on:
  push:  # Trigger on push to main branch
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
            pip install build

      - name: Build the package
        run: |
            python -m build

      - name: Install dependencies
        run: |
            pip install -r requirements.txt

      - name: Install custom package
        run: |
            pip install dist/ar_classification-0.1.0-py3-none-any.whl

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Model in Azure ML
        run: |
            python scripts/build_model.py

      - name: Register Model in Azure ML
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SP_ID: ${{ secrets.AZURE_SP_ID }}
          AZURE_SP_SECRET: ${{ secrets.AZURE_SP_SECRET }}
          AZURE_WORKSPACE_ID: ${{ secrets.AZURE_WORKSPACE_ID }}
        run: |
            python scripts/register_model.py

      - name: Deploy Model to Azure ML Endpoint
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SP_ID: ${{ secrets.AZURE_SP_ID }}
          AZURE_SP_SECRET: ${{ secrets.AZURE_SP_SECRET }}
          AZURE_WORKSPACE_ID: ${{ secrets.AZURE_WORKSPACE_ID }}
        run: |
            python scripts/deploy_model.py
