name: Deploy ML Model to Azure ML Studio

on:
  push:  # Trigger on push to main branch
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
            pip install -r requirements.txt

      - name: Install dependencies
        run: |
            pip install https://mmadata.blob.core.windows.net/custom-package/ar_classification-0.1.0-py3-none-any.whl?sp=r&st=2025-02-05T18:55:28Z&se=2025-02-06T02:55:28Z&spr=https&sv=2022-11-02&sr=b&sig=aI2CWRJ0%2BcJLiLV0%2FQVU42Z0bPbVhDxxreWWMHkr5Wc%3D

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register Model in Azure ML
        run: |
            python scripts/build_model.py

      - name: Register Model in Azure ML
        run: |
            python scripts/register_model.py

      - name: Deploy Model to Azure ML Endpoint
        run: |
            python scripts/deploy_model.py
